name: Merge master to dev  
on:  
  push:  
    branches:  
      - master  
  
jobs:  
  merge_master_to_dev:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2.1.1  
      - name: Merge master to dev  
        run: |  
          git fetch
          git branch -a
          git checkout dev  
          git merge --no-ff --no-edit master