name: Main Workflow  
  
on:  
  push:  
    branches:  
      - '*' # 触发器将在每个分支的push操作后触发  
  
jobs:  
  merge_request:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2.1.1  
      - name: Create merge request  
        run: |  
          echo "Creating merge request from ${{ github.sha }} to dev..."  
          # 在这里添加创建合并请求的命令，例如：  
          chmod +x ./create_merge_request.sh ${{ github.sha }} dev
