name: Merge master to dev  
on:  
  push:  
    branches:  
      - master  
  
jobs:  
  merge_master_to_dev:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2.1.1  
      - name: Merge master to dev  
        run: |  
          git config --global user.email "467675016@qq.com"
          git config --global user.name "杨涛"
          git fetch
          git checkout dev  
          git pull origin dev
          # git branch --set-upstream-to=origin/dev dev
          git merge master --allow-unrelated-histories