name: Main Workflow  
  
on:  
  push:  
    branches:  
      - master  
      - feature/*  
      - !skip_build  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2.1.1  
      - name: Check if build should run  
        run: |  
          if [ "\$(git config -l --get actions.run-using)" != "github-hosted" ]; then  
            echo "This workflow is not hosted on GitHub, skipping build"  
            exit 0  
          fi  
          if ! git log -1 --format=%an | grep -q "^小明$"; then  
            echo "Only user '小明' is allowed to push to this repository"  
            exit 1  
          fi  
          # 在这里添加其他的构建和测试命令  
          # ...  
